; =============================================================
; Lesson 16 -- WS2812 Addressable LEDs
; Fundamentals of C++ for Microcontrollers
; =============================================================
;
; Board : TENSTAR RP2350-USB (RP2350A, 16MB flash)
; Core  : ARM Cortex-M33 @ 150 MHz
; SDK   : Pico SDK via earlephilhower Arduino-Pico wrapper
;
; Onboard WS2812 RGB LED on GP22
; External 10-LED ring on GP15

[env:rp2350_usb]
platform  = https://github.com/maxgerhardt/platform-raspberrypi.git
board     = rpipico2
framework = arduino

board_build.core = earlephilhower

monitor_speed = 115200
