; Lesson 8: RAII, Memory Handling, Standard Libraries
; Board: ESP32-C3 Super Mini (Lolin C3 Mini)

[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200
build_flags = -std=gnu++17
build_unflags = -std=gnu++11
