; Lesson 4 - Structs and Pointers to Structs
; Embedded Systems Course 2026

[env:esp32-c3-devkitm-1]
platform  = espressif32
board     = esp32-c3-devkitm-1
framework = arduino

; Serial monitor
monitor_speed   = 115200
monitor_filters = esp32_exception_decoder

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -std=c++17
    -Wall
    -Wextra

; Upload speed
upload_speed = 921600
