#include <Arduino.h>
#include "button.h"
#include "led.h"

// ------------------------------------------------------------
// Lesson 9 homework — do NOT edit this file.
//
// Your task is to implement the missing methods in:
//   src/button.cpp   (constructor, isPressed)
//   src/led.cpp      (constructor, on, off, toggle, setDutyCycle)
//
// When your library is correct, this program should:
//   BTN0 held     -> red LED fades in  (1 s)
//   BTN0 released -> red LED fades out (1 s)
//   BTN1 press    -> green LED toggles
// ------------------------------------------------------------

drivers::Button btn0(0);
drivers::Button btn1(1);
drivers::Led    red(3,  0);
drivers::Led    grn(10, 1);

void IRAM_ATTR isr_btn0() { btn0.onISR(); }
void IRAM_ATTR isr_btn1() { btn1.onISR(); }

bool prevBtn1 = false;

void setup()
{
    Serial.begin(115200);
    Serial.println("Lesson 9 homework");

    attachInterrupt(digitalPinToInterrupt(0), isr_btn0, CHANGE);
    attachInterrupt(digitalPinToInterrupt(1), isr_btn1, CHANGE);
}

void loop()
{
    if (btn0.isPressed()) {
        red.fadeTo(255, 1000);
    } else {
        red.fadeTo(0, 1000);
    }

    bool currBtn1 = btn1.isPressed();
    if (currBtn1 && !prevBtn1) {
        grn.toggle();
        Serial.println("BTN1 pressed - green toggled");
    }
    prevBtn1 = currBtn1;

    red.update();

    static bool prevBtn0 = false;
    bool currBtn0 = btn0.isPressed();
    if (currBtn0 != prevBtn0) {
        Serial.print("BTN0 ");
        Serial.println(currBtn0 ? "pressed  -> fading in"
                                : "released -> fading out");
        prevBtn0 = currBtn0;
    }
}
